:wqapiVersion: apps/v1
kind: Deployment
metadata:
  name: DigitalBank
  labels:
    app: DBank
spec:
  replicas: 15
  selector:
    matchLabels:
      app: DBank
  template:
    metadata:
      labels:
        app: DBank
    spec:
      containers:
      - name: DigitalBankProject
        image: yaminianand/digitalbank_latest
        ports:
        - containerPort: 80  

---

apiVersion: v1
kind: Service
metadata:
  name: Bank-Service
spec:
  type: NodePort
  selector:
    app: DBank
  ports:
    - port: 80
      targetPort: 8080
                          



