apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitalbank
  labels:
    app: dbank
spec:
  replicas: 15
  selector:
    matchLabels:
      app: dbank
  template:
    metadata:
      labels:
        app: dbank
    spec:
      containers:
      - name: digitalbankproject
        image: yaminianand/digitalbank:latest
        ports:
        - containerPort: 80  

---

apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  type: NodePort
  selector:
    app: dbank
  ports:
    - port: 80
      targetPort: 8080
                          



